REM PROGRAMA DE BIENVENIDA
PRINT "SOY LA COMPUTADORA DE MAURICIO"
PRINT "TÚ QUIÉN ERES?"
INPUT N$
PRINT "HOLA "; N$; " MUCHO GUSTO EN CONOCERTE"
PRINT "TE GUSTAN LAS COMPUTADORAS"
PRINT "RESPONDE SI O NO"
INPUT A$
IF A$ = "SI" OR A$ = "NO" GOTO 110
GOTO 70
PRINT "QUIERES APRENDER BASIC?"
PRINT "RESPONDE SI O NO"
INPUT B$
IF B$ = "SI" OR B$ = "NO" GOTO 160
GOTO 120
IF A$ = "SI" AND B$ = "SI" GOTO 180
PRINT "VETE AL CUERNO! "; N$:END
PRINT "BIENVENIDO ENTRE NOSOTROS "; N$
END